# Generated by Django 5.0.4 on 2024-04-16 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video_url', 'Video URL'), ('pdf_url', 'PDF URL')], max_length=20, verbose_name='Contect Type')),
                ('content_data', models.TextField(verbose_name='Content Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'contents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_id'], name='contents_content_148f7d_idx')],
            },
        ),
    ]
