# Generated by Django 5.0.4 on 2024-04-16 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=255, verbose_name='Lesson Name')),
                ('lesson_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('quiz', 'Quiz')], max_length=20, verbose_name='Lesson Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': 'lessons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lesson_id'], name='lessons_lesson__7583ad_idx')],
            },
        ),
    ]
